# Generated by Django 3.2.11 on 2022-02-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('story_id', models.IntegerField(unique=True)),
                ('score', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('type', models.CharField(max_length=50)),
                ('descendants', models.IntegerField(default=0)),
                ('text', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('story_id', models.IntegerField(unique=True)),
                ('score', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('story_id', models.IntegerField(unique=True)),
                ('score', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('type', models.CharField(max_length=50)),
                ('descendants', models.IntegerField(default=0)),
                ('text', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
