# Generated by Django 3.2.11 on 2022-02-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('story_id', models.IntegerField(default=0, unique=True)),
                ('score', models.IntegerField(null=True)),
                ('text', models.TextField(default='', null=True)),
                ('time', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('type', models.CharField(max_length=50)),
                ('descendants', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'askstories',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('story_id', models.IntegerField(default=0, unique=True)),
                ('score', models.IntegerField(null=True)),
                ('text', models.TextField(default='', null=True)),
                ('time', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('type', models.CharField(max_length=50)),
                ('url', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'jobstories',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('story_id', models.IntegerField(default=0, unique=True)),
                ('score', models.IntegerField(null=True)),
                ('text', models.TextField(default='', null=True)),
                ('time', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('type', models.CharField(max_length=50)),
                ('descendants', models.IntegerField(default=0)),
                ('url', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'newstories',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('story_id', models.IntegerField(default=0, unique=True)),
                ('score', models.IntegerField(null=True)),
                ('text', models.TextField(default='', null=True)),
                ('time', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('type', models.CharField(max_length=50)),
                ('descendants', models.IntegerField(default=0)),
                ('url', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'showstories',
            },
        ),
    ]
