# Generated by Django 3.2.11 on 2022-02-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_ask_kids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='kids',
        ),
    ]
