# Generated by Django 3.2.11 on 2022-02-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_ask_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
