# Generated by Django 3.2.11 on 2022-02-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_job_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='descendants',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ask',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
