# Generated by Django 3.2.11 on 2022-02-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20220201_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='story_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
