# Generated by Django 3.2.11 on 2022-06-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_auth',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
