# Generated by Django 3.2.11 on 2022-06-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_image'),
        ('accounts', '0003_profile_google_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Movie'),
        ),
    ]
