# Generated by Django 3.2.11 on 2022-05-25 01:50

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220524_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.TextField(blank=True),
        ),
    ]
